---
services:
  code-server:
    image: finsss/llvm-develop-docker:latest
    container_name: llvm-develop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=123456
      - SUDO_PASSWORD=123456
      - DEFAULT_WORKSPACE=/workspace
    volumes:
      - D:\\Docker\\llvm-develop:/config
      - D:\\WorkSpace:/workspace
    ports:
      - 8444:8443
    restart: unless-stopped