name: ci

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Set Docker Image Tag
        id: set_tag
        run: |
          # Get the current system time in UTC and format it as YYYYMMDDHHMMSS
          TIMESTAMP=$(date -u +"%Y%m%d%H%M%S")
          echo "docker_image_tag=$TIMESTAMP" >> $GITHUB_OUTPUT
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: finsss/llvm-develop-docker:${{ steps.set_tag.outputs.docker_image_tag }}
